### ISSUE TITLE
Job Stories

### ISSUE THREAD

**Issue by dandevri** [Sanderoost/blok-tech#2]
Because of the lack of research your Job Stories are too generic and I can't really see which one you've picked to work on.

**Comment by Sanderoost** [comment]
Hi Danny,

I would like to work on a message function so the first job story:
1. Wanneer ik gematched ben met iemand, wil ik diegene een bericht kunnen sturen.

Before i do more reasearch on this i would like to know if you think this is possible?
Im not familiar with sockets so maybe i could store the messages in the database and use user id's to direct the messages to the right person?

**Comment by dandevri** [comment]
I wouldn't focus on chatting as a Job Story. 

`Sockets` and `WebRTC` aren't part of this course. I would pick another feature to work on. If learning this is one of your own learning goals you can always enhance your dating app by incorporating messaging with `[socket.io](https://socket.io/)`.

**Comment by Sanderoost** [comment]
Allright sounds difficult but really intresting so ill have look at it if i have some spare time left.

Is this one better:
 "Wanneer ik een profiel aanmaak, wil ik aangeven wat mijn interesses zijn en zo mijn kans vergroten op een betere match. "

Also, do you prefer the wiki to be in dutch or english?

**Comment by dandevri** [comment]
> "Wanneer ik een profiel aanmaak, wil ik aangeven wat mijn interesses zijn en zo mijn kans vergroten op een betere match. "

Too vague and generic, try find a focus group! 

> Also, do you prefer the wiki to be in dutch or english?

For the wiki it doesn't really matter, but if you expect other developers to read it (outside the classroom) it's a good practice to do it in english.

**Comment by Sanderoost** [comment]
Okay i'm just going to keep on trying..

"When im creating a profile, i want to let people know which movies and tv shows i like so i can find someone with the same taste in movies and tv shows."

or

"When im creating a profile, i want to let people know what genre in movies and tv shows i like so i can find someone with the same taste in movies and tv shows."

Good point, i'll change it to english!
